-- =============================================================================
-- PROCESO AUTOMATIZADO TELEVENTAS_EJECUTIVOS_GROUPED
-- Parametros esperados: {PERIODO} (ejemplo: '202608')
-- =============================================================================

-- 1. Limpieza de espacios en periodo de la tabla origen
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS
SET PERIODO = TRIM(PERIODO)
WHERE PERIODO LIKE '%{PERIODO}%';

-- 2. Limpieza de datos previos en la tabla destino para garantizar idempotencia
DELETE FROM DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED
WHERE TRIM(PERIODO) = '{PERIODO}';

-- 3. Inserción de los registros del periodo activo desde TELEVENTAS_EJECUTIVOS
INSERT INTO DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED (
    PERIODO,
    REG_EJECUTIVO,
    NOM_EJECUTIVO,
    REG_SUPERVISOR,
    NOM_SUPERVISOR,
    REG_JEFE,
    NOM_JEFE,
    EQUIPO,
    SUB_EQUIPO,
    SUBGERENTE,
    COD_ANTIG,
    NOM_EJECUTIVO_OLD,
    CODIGO,
    SUBGERENTE_SHORT,
    JEFE_SHORT,
    SUPERVISOR_SHORT
)
SELECT DISTINCT
    TRIM(PERIODO),
    REG_EJECUTIVO,
    NOM_EJECUTIVO,
    REG_SUPERVISOR,
    NOM_SUPERVISOR,
    REG_JEFE,
    NOM_JEFE,
    EQUIPO,
    SUB_EQUIPO,
    SUBGERENTE,
    TIPO AS COD_ANTIG,
    NOM_EJECUTIVO_OLD,
    CODIGO,
    NULL AS SUBGERENTE_SHORT,
    NULL AS JEFE_SHORT,
    NULL AS SUPERVISOR_SHORT
FROM DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS
WHERE TRIM(PERIODO) = '{PERIODO}';

-- 3. Limpieza de espacios en la tabla agrupada
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED
SET PERIODO = TRIM(PERIODO)
WHERE PERIODO LIKE '%{PERIODO}%';

-- 3.b Actualización del campo CODIGO (PERIODO || '_' || REG_EJECUTIVO) en ambas tablas
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS
SET CODIGO = TRIM(PERIODO) || '_' || TRIM(REG_EJECUTIVO)
WHERE TRIM(PERIODO) = '{PERIODO}';

UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED
SET CODIGO = TRIM(PERIODO) || '_' || TRIM(REG_EJECUTIVO)
WHERE TRIM(PERIODO) = '{PERIODO}';

-- 4. Actualización de SUBGERENTE_SHORT
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUBGERENTE_SHORT = 'TITA ARNAO' WHERE SUBGERENTE = 'CECILIA DEL ROSARIO ARNAO Y CACHO' AND (SUBGERENTE_SHORT IS NULL OR SUBGERENTE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUBGERENTE_SHORT = 'JAIRO ROMERO' WHERE SUBGERENTE = 'JAIRO EMILIO ROMERO CALDERON' AND (SUBGERENTE_SHORT IS NULL OR SUBGERENTE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUBGERENTE_SHORT = 'DIEGO VEGAS' WHERE SUBGERENTE = 'DIEGO VEGAS LA ROSA' AND (SUBGERENTE_SHORT IS NULL OR SUBGERENTE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUBGERENTE_SHORT = 'CHRISTIAN ALVARADO' WHERE SUBGERENTE = 'CHRISTIAN RAMON ALVARADO PEREZ' AND (SUBGERENTE_SHORT IS NULL OR SUBGERENTE_SHORT = '');

-- 5. Actualización de JEFE_SHORT
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET JEFE_SHORT = 'BRENDIE VERGARA' WHERE REG_JEFE = 'B47190' AND (JEFE_SHORT IS NULL OR JEFE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET JEFE_SHORT = 'ANDRES SALDA A' WHERE REG_JEFE = 'B16076' AND (JEFE_SHORT IS NULL OR JEFE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET JEFE_SHORT = 'KATHERINA DE LA VEGA' WHERE REG_JEFE = 'S30931' AND (JEFE_SHORT IS NULL OR JEFE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET JEFE_SHORT = 'ENMANUELLA MAMANI' WHERE REG_JEFE = 'B19333' AND (JEFE_SHORT IS NULL OR JEFE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET JEFE_SHORT = 'GIOVANNI GIRALDO' WHERE REG_JEFE = 'B17635' AND (JEFE_SHORT IS NULL OR JEFE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET JEFE_SHORT = 'GUILLERMO VIA' WHERE REG_JEFE = 'B12266' AND (JEFE_SHORT IS NULL OR JEFE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET JEFE_SHORT = 'JACQUELINE CARRIL' WHERE REG_JEFE = 'B27642' AND (JEFE_SHORT IS NULL OR JEFE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET JEFE_SHORT = 'JACQUELINE MONDRAGON' WHERE REG_JEFE = 'B41874' AND (JEFE_SHORT IS NULL OR JEFE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET JEFE_SHORT = 'J. DANIEL GUTIERREZ' WHERE REG_JEFE = 'B27811' AND (JEFE_SHORT IS NULL OR JEFE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET JEFE_SHORT = 'NATALIA LAITHER' WHERE REG_JEFE = 'B14445' AND (JEFE_SHORT IS NULL OR JEFE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET JEFE_SHORT = 'LUIS PRETELL' WHERE REG_JEFE = 'B21416' AND (JEFE_SHORT IS NULL OR JEFE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET JEFE_SHORT = 'MA. LUISA FERRADAS' WHERE REG_JEFE = 'B39779' AND (JEFE_SHORT IS NULL OR JEFE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET JEFE_SHORT = 'NORYBELL ROLLET' WHERE REG_JEFE = 'B19392' AND (JEFE_SHORT IS NULL OR JEFE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET JEFE_SHORT = 'SAUL LLERENA' WHERE REG_JEFE = 'B12599' AND (JEFE_SHORT IS NULL OR JEFE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET JEFE_SHORT = 'VANESSA DELGADO' WHERE REG_JEFE = 'B23519' AND (JEFE_SHORT IS NULL OR JEFE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET JEFE_SHORT = 'TRASLADO' WHERE NOM_JEFE = 'TRASLADO' AND (JEFE_SHORT IS NULL OR JEFE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET JEFE_SHORT = 'J. PABLO GONZALES' WHERE REG_JEFE = 'B17732' AND (JEFE_SHORT IS NULL OR JEFE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET JEFE_SHORT = 'GIAN ALARCON' WHERE REG_JEFE = 'B33216' AND (JEFE_SHORT IS NULL OR JEFE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET JEFE_SHORT = 'ALEX TORRES' WHERE REG_JEFE = 'B16830' AND (JEFE_SHORT IS NULL OR JEFE_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET JEFE_SHORT = 'LUIS SILVERA' WHERE REG_JEFE = 'B45830' AND (JEFE_SHORT IS NULL OR JEFE_SHORT = '');

-- 6. Actualización de SUPERVISOR_SHORT
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'MERCE ALARCON' WHERE REG_SUPERVISOR = 'B23510' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'ALAN DAVILA' WHERE REG_SUPERVISOR = 'B28616' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'ANA ZAMBRANO' WHERE REG_SUPERVISOR = 'B17470' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'ANALI TOVAR' WHERE REG_SUPERVISOR = 'B24674' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'BRUNO MIRANDA' WHERE REG_SUPERVISOR = 'B43648' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'CLAUDIA ATARAMA' WHERE REG_SUPERVISOR = 'B13802' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'CARLOS MACEDO' WHERE REG_SUPERVISOR = 'B46946' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'CATHERINE ESPINOZA' WHERE REG_SUPERVISOR = 'B15241' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'CESSY RAMIREZ' WHERE REG_SUPERVISOR = 'B10961' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'CHRISTIAN RIOS' WHERE REG_SUPERVISOR = 'B22640' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'CINTHYA PAZ' WHERE REG_SUPERVISOR = 'B12340' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'DANIEL ARTEAGA' WHERE REG_SUPERVISOR = 'B14426' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'GABRIEL LLANOS' WHERE REG_SUPERVISOR = 'B11383' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'GIANMARCO TORRES' WHERE REG_SUPERVISOR = 'B11103' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'GIOVANNA QUINTANA' WHERE REG_SUPERVISOR = 'B18958' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'ITALO GONZALES' WHERE REG_SUPERVISOR = 'B17153' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'KAREN GUTIERREZ' WHERE REG_SUPERVISOR = 'B29861' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'SUSAN OLIVEROS' WHERE REG_SUPERVISOR = 'B44685' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'MA. TERESA VELA' WHERE REG_SUPERVISOR = 'B10318' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'MARTHA HERRERA' WHERE REG_SUPERVISOR = 'B35078' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'MARTIN EYZAGUIRRE' WHERE REG_SUPERVISOR = 'B31518' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'MARLON PONTE' WHERE REG_SUPERVISOR = 'B41726' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'MIGUEL VASQUEZ' WHERE REG_SUPERVISOR = 'B41906' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'MILAGROS CABANILLAS' WHERE REG_SUPERVISOR = 'B22522' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'MONICA REYNA' WHERE REG_SUPERVISOR = 'B12999' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'MONICA ZAVALA' WHERE REG_SUPERVISOR = 'B17729' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'NATALIA SARMIENTO' WHERE REG_SUPERVISOR = 'B44770' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'LUIS ESCUDERO' WHERE REG_SUPERVISOR = 'B40689' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'ROSA REGALADO' WHERE REG_SUPERVISOR = 'B21769' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'SALA 12' WHERE REG_SUPERVISOR = 'B00000' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'SARA TORRES' WHERE REG_SUPERVISOR = 'B14058' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'YANIRE DIESTRO' WHERE REG_SUPERVISOR = 'B23324' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'JESUS ESCOBAR' WHERE REG_SUPERVISOR = 'B09345' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'ALFREDO PONCE' WHERE REG_SUPERVISOR = 'B20324' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'ANDRES SALDA A' WHERE REG_SUPERVISOR = 'B16076' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'AYDA GALLO' WHERE REG_SUPERVISOR = 'B20508' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'BRUNO LOMBARDI' WHERE REG_SUPERVISOR = 'B09334' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'CATALINA ATARAMA' WHERE REG_SUPERVISOR = 'B22851' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'CORINTIA PHOCCO' WHERE REG_SUPERVISOR = 'B32657' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'DIANA ARRIETA' WHERE REG_SUPERVISOR = 'B23764' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'DIANA RUBINA' WHERE REG_SUPERVISOR = 'B12151' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'ENRIQUE JURO' WHERE REG_SUPERVISOR = 'B16434' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'GEMMA RODRIGUEZ' WHERE REG_SUPERVISOR = 'B16402' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'GIAN CARLO ALARCON' WHERE REG_SUPERVISOR = 'B33216' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'JESUS DAVILA' WHERE REG_SUPERVISOR = 'B17098' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'J. DIEGO ARMAS' WHERE REG_SUPERVISOR = 'B30752' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'EVELYN MONTENEGRO' WHERE REG_SUPERVISOR = 'B30621' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'HARRY GUERRERO' WHERE REG_SUPERVISOR = 'B11661' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'INES REYES' WHERE REG_SUPERVISOR = 'B09367' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'JOHNNY SANTIVA EZ' WHERE REG_SUPERVISOR = 'B24256' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'JONATHAN ADANAQUE' WHERE REG_SUPERVISOR = 'B42116' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'KELLY GUZMAN' WHERE REG_SUPERVISOR = 'B33023' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'MARCO SANTISTEBAN' WHERE REG_SUPERVISOR = 'B23465' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'MA. ELENA LEON' WHERE REG_SUPERVISOR = 'B12771' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'MARILIN AGUILAR' WHERE REG_SUPERVISOR = 'B23879' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'JHONATHAN CHAVEZ' WHERE REG_SUPERVISOR = 'B39675' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'JHUNIOR ARENAS' WHERE REG_SUPERVISOR = 'B23154' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'KATHERINA DE LA VEGA' WHERE REG_SUPERVISOR = 'S30931' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'MARIA VILLACORTA' WHERE REG_SUPERVISOR = 'B09116' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'MA. GRACIA DAVILA' WHERE REG_SUPERVISOR = 'B26422' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'MA. LUISA FERRADAS' WHERE REG_SUPERVISOR = 'B39779' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'MARILYN PRECIADO' WHERE REG_SUPERVISOR = 'B28107' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'RAFAEL RUEDA' WHERE REG_SUPERVISOR = 'B37184' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'VERONICA ORTEGA' WHERE REG_SUPERVISOR = 'B34023' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'YDALLI MENDOZA' WHERE REG_SUPERVISOR = 'B14632' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'CARLOS DE LA CRUZ' WHERE REG_SUPERVISOR = 'B27855' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'TRASLADO' WHERE NOM_SUPERVISOR = 'TRASLADO' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUPERVISOR_SHORT = 'VACANTE' WHERE NOM_SUPERVISOR = 'VACANTE' AND (SUPERVISOR_SHORT IS NULL OR SUPERVISOR_SHORT = '');

-- 7. Actualización retroactiva de supervisor
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED 
SET NOM_SUPERVISOR = 'MARILYN JANET PRECIADO CHERO',
    REG_SUPERVISOR = 'B28107',
    SUPERVISOR_SHORT = 'MARILYN PRECIADO'
WHERE SUB_EQUIPO = 'R_MULTI'
  AND SUPERVISOR_SHORT = 'ANALI TOVAR'
  AND PERIODO >= '202501';

-- 8. Estandarización de SUB_EQUIPO
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUB_EQUIPO = 'BNC' WHERE EQUIPO = 'BANCA NEGOCIOS' AND REG_SUPERVISOR = 'B10961';
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUB_EQUIPO = 'BNB' WHERE EQUIPO = 'BANCA NEGOCIOS' AND REG_SUPERVISOR <> 'B10961';
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUB_EQUIPO = 'CONV_TLV' WHERE SUB_EQUIPO IN ('CONV');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUB_EQUIPO = 'R_MULTI' WHERE SUB_EQUIPO IN ('RTC', 'MULTI');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUB_EQUIPO = 'R_CO' WHERE SUB_EQUIPO IN ('RCO');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUB_EQUIPO = 'GDP' WHERE SUB_EQUIPO IN ('PRT');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET SUB_EQUIPO = 'CHIP' WHERE SUB_EQUIPO IN ('HIP');

-- 9. Estandarización de EQUIPO
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET EQUIPO = 'BANCA NEGOCIOS' WHERE SUB_EQUIPO IN ('BNB', 'BNC');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET EQUIPO = 'GDP' WHERE EQUIPO = 'POST VENTA';
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET EQUIPO = 'SELECT' WHERE EQUIPO = 'RENTA ALTA';
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET EQUIPO = 'RET. CONV' WHERE SUB_EQUIPO IN ('R_CO');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET EQUIPO = 'RET. MULTI' WHERE SUB_EQUIPO IN ('R_MULTI', 'RTC');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET EQUIPO = 'TLV CASH' WHERE SUB_EQUIPO IN ('PP', 'EC', 'CD');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET EQUIPO = 'TLV CHIP' WHERE SUB_EQUIPO IN ('CHIP');
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET EQUIPO = 'TLV TC' WHERE SUB_EQUIPO = 'TC';
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET EQUIPO = 'TLV PAY' WHERE SUB_EQUIPO = 'PAY';

-- 10. Normalización de nombre de ejecutivo específico
UPDATE DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED SET NOM_EJECUTIVO = 'MARITZA ESMERALDA DIAZ MALQUI' WHERE REG_EJECUTIVO = 'B34910';

-- 11. Refresco de vista
REPLACE VIEW DLAB_GEC.V_EXP_TELEVENTAS_EJECUTIVOS_GROUPED_VIEW AS                                             
(                                            
SELECT                                             
	CODIGO,
	PERIODO,
	REG_EJECUTIVO,
	NOM_EJECUTIVO,
	REG_SUPERVISOR,
	NOM_SUPERVISOR,
	SUPERVISOR_SHORT,
	REG_JEFE,
	NOM_JEFE,
	JEFE_SHORT,
	EQUIPO,
	SUB_EQUIPO,
	SUBGERENTE,
	SUBGERENTE_SHORT,
	COD_ANTIG,
	NOM_EJECUTIVO_OLD
FROM DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS_GROUPED
WHERE SUB_EQUIPO NOT IN ('PAY', 'CON_PROV', 'CON_LIMA')
);
