-- =====================================================================
-- 02_KRI_RESUMEN_TOTAL.SQL
-- Cierre KRI: Inserción mensual del resumen total de ventas sin audio
-- y teléfonos no autorizados para el periodo cerrado {PERIODO_ANTERIOR}
-- =====================================================================

INSERT INTO DLAB_GEC.M_KRI_RESUMEN_TOTAL (
    PERIODO,
    VENTAS,
    SIN_AUDIO,
    TOTAL_TLF,
    TLF_NOVALIDO,
    TOTAL_EVAL,
    EVAL_MI
)
WITH VNT AS (
    SEL 
        CAST(MESDESEMBOLSO AS INTEGER) AS PERIODO,
        COUNT(TIP_CLIENTE) AS VENTAS,
        COUNT(TIP_CLIENTE) - COUNT(ORIGEN_LLAMADA) AS SIN_AUDIO
    FROM DLAB_GEC.T_EXP_KRI_VENTAS_SINAUDIO
    WHERE CAST(MESDESEMBOLSO AS INTEGER) = CAST('{PERIODO_ANTERIOR}' AS INTEGER)
    GROUP BY 1
),
TLF AS (
    SEL 
        CAST(SUBSTR(CAST(FECDESEMB AS VARCHAR(10)), 1, 4) || SUBSTR(CAST(FECDESEMB AS VARCHAR(10)), 6, 2) AS INTEGER) AS PERIODO,
        COUNT(NUM_DOCUMENTO) AS TOTAL_TLF,
        COUNT(NUM_DOCUMENTO) - COUNT(TIPO_VAL) AS TLF_NOVALIDO
    FROM DLAB_GEC.T_EXP_KRI_TELF_NO_AUTORIZADO
    WHERE CAST(SUBSTR(CAST(FECDESEMB AS VARCHAR(10)), 1, 4) || SUBSTR(CAST(FECDESEMB AS VARCHAR(10)), 6, 2) AS INTEGER) = CAST('{PERIODO_ANTERIOR}' AS INTEGER)
    GROUP BY 1
)
SEL 
    COALESCE(v.PERIODO, t.PERIODO) AS PERIODO,
    COALESCE(v.VENTAS, 0) AS VENTAS,
    COALESCE(v.SIN_AUDIO, 0) AS SIN_AUDIO,
    COALESCE(t.TOTAL_TLF, 0) AS TOTAL_TLF,
    COALESCE(t.TLF_NOVALIDO, 0) AS TLF_NOVALIDO,
    NULL AS TOTAL_EVAL,
    NULL AS EVAL_MI
FROM VNT v
FULL OUTER JOIN TLF t 
    ON v.PERIODO = t.PERIODO;
