-- =============================================================================
-- TABLA DESTINO SPEECH ANALYTICS TCAD
-- =============================================================================
CREATE MULTISET TABLE DLAB_GEC.M_EXP_DATA_TCAD_SA ,FALLBACK ,
 NO BEFORE JOURNAL,
 NO AFTER JOURNAL,
 CHECKSUM = DEFAULT,
 DEFAULT MERGEBLOCKRATIO,
 MAP = TD_MAP1
 (
    TCAD_A FLOAT,
    TCAD_B FLOAT,
    TELEF_IN VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
    COLA VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
    DNI VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
    REG_EV VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
    NOM_EV VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
    SUPERVISOR VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
    TIPIFICACION VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
    DIRECCION VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
    TELEF_OUT VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
    DURACION INTEGER,
    FECHA_LLAMADA TIMESTAMP(6),
    CONID VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
    CODIGO VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
    VENTA_TC VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
    VENTA_TCAD VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
    PERIODO VARCHAR(6) CHARACTER SET LATIN NOT CASESPECIFIC,
    OFRE_TCAD FLOAT
 )
PRIMARY INDEX ( CONID );

-- =============================================================================
-- TABLA DESTINO CROSS TCAD
-- =============================================================================
CREATE MULTISET TABLE DLAB_GEC.M_EXP_CROSS_TCAD,FALLBACK ,
 NO BEFORE JOURNAL,
 NO AFTER JOURNAL,
 CHECKSUM = DEFAULT,
 DEFAULT MERGEBLOCKRATIO,
 MAP = TD_MAP1
 (
    PERIODO VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC, 
    DNI VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
    REG_EJECUTIVO VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
    EJECUTIVO VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
    SUPERVISOR VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
    INDICADOR VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
    FECHA_SOLICITUD TIMESTAMP(6),
    FECHA_APROBACION TIMESTAMP(6),
    FLG_VALIDO VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
    CODIGO VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC
 )
PRIMARY INDEX ( DNI, REG_EJECUTIVO, FECHA_SOLICITUD );

-- =============================================================================
-- VISTA DE VENTAS TC (FILTRADA Y NORMALIZADA)
-- =============================================================================
REPLACE VIEW DLAB_GEC.V_EXP_VENTAS_TC_TCAD AS
SELECT 
    hist.PERIODO_VAL AS MESDESEMBOLSO,
    'DTC' AS TIP_CLIENTE,
    'TLV' AS GESTION,
    hist.PROMOTOR_CD AS CODPROMOT,
    hist.PROMOTOR_NM AS NOMPROMOT,
    hist.SUPERVISOR_NM AS NOMSUPER,
    hist.EQUIPOVENTA_DSC AS EQUIPO,
    hist.SUBEQUIPOVENTA_DSC AS SUB_EQUIPO,
    hist.APROBACIONEXPEDADQ_FC AS FECDESEMB,
    LPAD(CAST(EXTRACT(DAY FROM hist.APROBACIONEXPEDADQ_FC) AS VARCHAR(2)), 2, '0') AS DIA,
    LTRIM(RTRIM(hist.DOCUMENTO_NUM)) AS CODDOC,
    hist.LINEATC_AMT AS MONTO_APROB,
    hist.ESTADOSOLICITUD_DSC AS ESTADO, 
    hist.TIPOTCAPROBADA_DSC AS TIPOAPROB, 
    hist.DISPOSICIONEFECTIVO_AMT AS DISPOEFECT, 
    hist.ESTADOCIVILCLI_DSC AS ESTACIVIL, 
    hist.SITUACIONLABORALCLI_DSC AS SITLABORAL,
    hist.CORREOCLI_DSC AS CORREO, 
    hist.TELEFONOCELULAR_NUM AS TELCELUL,
    hist.CLIENTE_NM AS NOMCLIENTE,
    hist.INGRESOEXPEDADQ_FC AS ECREGIST,
    hist.ENTREGATC_FC AS FECENTREGA, 
    hist.ACTIVATC_FC AS FECACTIVA, 
    hist.TARJETA_NUM
FROM E_DW_VIEWS.V_FCT_RT_TC_HISTORICO AS hist
INNER JOIN DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS AS ejec
    ON hist.PROMOTOR_CD = ejec.REG_EJECUTIVO
   AND ejec.SUB_EQUIPO = 'TC'
WHERE hist.MESINGRESOEXPEDADQ_DSC >= '202608'
  AND hist.EQUIPOVENTA_DSC IN ('TLV TARJETAS', 'Televentas')
  AND hist.ESTADOSOLICITUD_DSC = 'Aprobado'
  AND hist.TIPOTRAMITE_DSC <> 'MIGRACIÓN TC'
  AND hist.OPERACION_CD IN (1, 2)
  AND hist.ESTADOSOLICITUD_CD = 3;

-- =============================================================================
-- VISTA FUNNEL TCAD
-- =============================================================================
REPLACE VIEW DLAB_GEC.V_FNL_TCAD_SIMPLE AS
WITH base AS (
    SELECT
        CODDOC,
        CODPROMOT,
        NOMPROMOT AS NOMBRE_EJECUTIVO,
        NOMSUPER,
        CAST(FECDESEMB AS DATE) AS FECHA_VENTA_TC,
        (EXTRACT(YEAR FROM CAST(FECDESEMB AS DATE)) * 100 + EXTRACT(MONTH FROM CAST(FECDESEMB AS DATE))) AS PERIODO,
        CASE
            WHEN EXTRACT(DAY FROM CAST(FECDESEMB AS DATE)) BETWEEN 1 AND 7 THEN 'Semana 01'
            WHEN EXTRACT(DAY FROM CAST(FECDESEMB AS DATE)) BETWEEN 8 AND 14 THEN 'Semana 02'
            WHEN EXTRACT(DAY FROM CAST(FECDESEMB AS DATE)) BETWEEN 15 AND 21 THEN 'Semana 03'
            WHEN EXTRACT(DAY FROM CAST(FECDESEMB AS DATE)) >= 22 THEN 'Semana 04'
            ELSE 'Fuera de rango'
        END AS SEMANA,
        1 AS VENTA_TC
    FROM DLAB_GEC.V_EXP_VENTAS_TC_TCAD
),
sa_dia AS (
    SELECT
        LPAD(TRIM(DNI), 8, '0') AS CODDOC,
        TRIM(REG_EV) AS CODPROMOT,
        CAST(FECHA_LLAMADA AS DATE) AS FECHA_LLAMADA,
        MAX(CASE WHEN OFRE_TCAD > 0 THEN 1 ELSE 0 END) AS OFRE_TCAD,
        MAX(CASE WHEN TCAD_A > 0 THEN 1 ELSE 0 END) AS OFER_A,
        MAX(CASE WHEN TCAD_B > 0 THEN 1 ELSE 0 END) AS OFER_B
    FROM DLAB_GEC.M_EXP_DATA_TCAD_SA
    GROUP BY 1, 2, 3
),
speech AS (
    SELECT
        base.CODDOC,
        base.CODPROMOT,
        base.FECHA_VENTA_TC,
        COALESCE(sa_dia.OFRE_TCAD, 0) AS OFRE_TCAD,
        COALESCE(sa_dia.OFER_A, 0) AS OFER_A,
        COALESCE(sa_dia.OFER_B, 0) AS OFER_B
    FROM base
    LEFT JOIN sa_dia
        ON sa_dia.CODDOC = base.CODDOC
       AND sa_dia.CODPROMOT = TRIM(base.CODPROMOT)
       AND sa_dia.FECHA_LLAMADA = base.FECHA_VENTA_TC
),
tcad AS (
    SELECT
        base.CODDOC,
        CASE WHEN COUNT(t.CODIGO) > 0 THEN 1 ELSE 0 END AS VENTA_TCAD_FLAG,
        COUNT(t.CODIGO) AS CANT_TCAD
    FROM base
    LEFT JOIN DLAB_GEC.M_EXP_CROSS_TCAD AS t
        ON LPAD(TRIM(t.DNI), 8, '0') = base.CODDOC
       AND t.INDICADOR = 'CROSS TC AD'
    GROUP BY base.CODDOC
)
SELECT
    base.PERIODO,
    base.SEMANA,
    base.FECHA_VENTA_TC,
    base.CODDOC,
    base.CODPROMOT,
    base.NOMBRE_EJECUTIVO,
    base.NOMSUPER,
    base.VENTA_TC,
    speech.OFRE_TCAD,
    speech.OFER_A,
    speech.OFER_B,
    COALESCE(tcad.VENTA_TCAD_FLAG, 0) AS VENTA_TCAD_FLAG,
    COALESCE(tcad.CANT_TCAD, 0) AS CANT_TCAD
FROM base
LEFT JOIN speech
    ON speech.CODDOC = base.CODDOC
   AND speech.CODPROMOT = base.CODPROMOT
   AND speech.FECHA_VENTA_TC = base.FECHA_VENTA_TC
LEFT JOIN tcad
    ON tcad.CODDOC = base.CODDOC;

-- =============================================================================
-- VISTA FACT TCAD
-- =============================================================================
REPLACE VIEW DLAB_GEC.V_FCT_TCAD AS
SELECT
    LPAD(TRIM(t.DNI), 8, '0') AS CODDOC,
    TRIM(t.CODIGO) AS CODIGO_TCAD,
    SUBSTR(TRIM(t.CODIGO), 1, 6) AS PERIODO,
    1 AS TCAD_VENDIDA
FROM DLAB_GEC.M_EXP_CROSS_TCAD AS t
WHERE t.INDICADOR = 'CROSS TC AD';

-- =============================================================================
-- VISTA FACT TCAD ATRIBUIDO
-- =============================================================================
REPLACE VIEW DLAB_GEC.V_FCT_TCAD_ATRIB AS
WITH tcad_base AS (
    SELECT
        LPAD(TRIM(t.DNI), 8, '0') AS CODDOC,
        TRIM(t.CODIGO) AS CODIGO_TCAD,
        SUBSTR(TRIM(t.CODIGO), 1, 6) AS PERIODO,
        1 AS TCAD_VENDIDA
    FROM DLAB_GEC.M_EXP_CROSS_TCAD AS t
    WHERE t.INDICADOR = 'CROSS TC AD'
),
venta_tc_mes AS (
    SELECT
        f.CODDOC,
        CAST(f.PERIODO AS VARCHAR(6)) AS PERIODO,
        f.FECHA_VENTA_TC,
        f.CODPROMOT,
        f.NOMSUPER
    FROM DLAB_GEC.V_FNL_TCAD_SIMPLE AS f
)
SELECT
    tcad_base.CODDOC,
    tcad_base.CODIGO_TCAD,
    tcad_base.PERIODO,
    venta_tc_mes.FECHA_VENTA_TC,
    venta_tc_mes.CODPROMOT,
    venta_tc_mes.NOMSUPER,
    tcad_base.TCAD_VENDIDA
FROM tcad_base
INNER JOIN venta_tc_mes
    ON venta_tc_mes.CODDOC = tcad_base.CODDOC
   AND venta_tc_mes.PERIODO = tcad_base.PERIODO;
