-- =============================================================================
-- PILOTO NO VENTA: DDL TABLA STAGE LIGERA EN TERADATA (22 COLUMNAS)
-- Corresponde a la plantilla P031-PILOTO_NO_VENTA
-- =============================================================================
CREATE MULTISET TABLE DLAB_GEC.M_EXP_STAGE_NO_VENTA_P031 ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ID_CONTACTO BIGINT,
      DNI VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      REG_EV VARCHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC,
      NOM_ASESOR VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      COLA VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      TIPIFICACION VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      FECHA_LLAMADA TIMESTAMP(6),
      DURACION INTEGER,
      T_SILENCIO INTEGER,
      PCT_SILENCIO FLOAT,
      MDO_GENERAL FLOAT,
      MDO_TLV FLOAT,
      OBJ_TASA_ALTA FLOAT,
      OBJ_LO_PENSARA FLOAT,
      OBJ_SIN_INTERES FLOAT,
      OBJ_COMPETENCIA FLOAT,
      OBJ_ENDEUDAMIENTO FLOAT,
      OBJ_OCUPADO FLOAT,
      OBJ_MALA_EXP FLOAT,
      OBJ_MEMBRESIA FLOAT,
      CIERRE_TRANSV FLOAT,
      CIERRE_TLV FLOAT
     )
PRIMARY INDEX ( DNI ,REG_EV ,FECHA_LLAMADA );
