-- =============================================================================
-- PILOTO NO VENTA: DDL TABLA STAGE LIGERA EN TERADATA (22 COLUMNAS)
-- Corresponde a la plantilla P031-PILOTO_NO_VENTA
-- =============================================================================
CREATE MULTISET TABLE DLAB_GEC.M_EXP_STAGE_NO_VENTA ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ID_CONTACTO BIGINT,
      DNI VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      REG_EV VARCHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC,
      NOM_ASESOR VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      COLA VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      TIPIFICACION VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      FECHA_LLAMADA TIMESTAMP(6),
      DURACION INTEGER,
      T_SILENCIO INTEGER,
      PCT_SILENCIO FLOAT,
      MDO_GENERAL FLOAT,
      MDO_TLV FLOAT,
      OBJ_TASA_ALTA FLOAT,
      OBJ_LO_PENSARA FLOAT,
      OBJ_SIN_INTERES FLOAT,
      OBJ_COMPETENCIA FLOAT,
      OBJ_ENDEUDAMIENTO FLOAT,
      OBJ_OCUPADO FLOAT,
      OBJ_MALA_EXP FLOAT,
      OBJ_MEMBRESIA FLOAT,
      CIERRE_TRANSV FLOAT,
      CIERRE_TLV FLOAT
     )
PRIMARY INDEX ( DNI ,REG_EV ,FECHA_LLAMADA );

-- =============================================================================
-- PILOTO NO VENTA: DDL TABLA HISTÓRICA FINAL EN TERADATA
-- =============================================================================
CREATE MULTISET TABLE DLAB_GEC.M_EXP_PILOTO_NO_VENTA ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      PERIODO VARCHAR(6) CHARACTER SET LATIN NOT CASESPECIFIC,
      ID_CONTACTO BIGINT,
      DNI VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      REG_EV VARCHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC,
      NOM_ASESOR VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      FECHA_LLAMADA DATE,
      COLA VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      TIPIFICACION VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      DURACION INTEGER,
      T_SILENCIO INTEGER,
      PCT_SILENCIO FLOAT,
      FLAG_MANEJA_OBJECION BYTEINT,
      FLAG_OBJ_TASA_ALTA BYTEINT,
      FLAG_OBJ_LO_PENSARA BYTEINT,
      FLAG_OBJ_SIN_INTERES BYTEINT,
      FLAG_OBJ_COMPETENCIA BYTEINT,
      FLAG_OBJ_ENDEUDAMIENTO BYTEINT,
      FLAG_OBJ_OCUPADO BYTEINT,
      FLAG_OBJ_MALA_EXP BYTEINT,
      FLAG_OBJ_MEMBRESIA BYTEINT,
      FLAG_CIERRE_SPEECH BYTEINT,
      FLAG_VENTA_REAL BYTEINT,
      PRODUCTO_VENTA_REAL VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      DIAGNOSTICO_GESTION VARCHAR(60) CHARACTER SET LATIN NOT CASESPECIFIC
     )
PRIMARY INDEX ( PERIODO ,DNI ,REG_EV ,FECHA_LLAMADA );

