-- =============================================================================
-- PILOTO NO VENTA: CRUCE TABLA STAGE LIGERA VS VENTAS REALES EN TERADATA
-- Parametro esperado: {PERIODO} (Ejemplo: '202608')
-- =============================================================================

-- 1. Deduplicación de Ventas Reales por Producto para el periodo activo
CREATE VOLATILE TABLE VT_VENTAS_TC_DEDUP AS (
    SELECT CODDOC, CODPROMOT, DIA
    FROM (
        SELECT CODDOC, CODPROMOT, DIA,
               ROW_NUMBER() OVER (PARTITION BY CODDOC, CODPROMOT, DIA ORDER BY CODDOC) AS rn
        FROM DLAB_GEC.M_EXP_VENTAS_TC
        WHERE TRIM(CAST(MESDESEMBOLSO AS VARCHAR(10))) = '{PERIODO}'
    ) t WHERE rn = 1
) WITH DATA PRIMARY INDEX (CODDOC, CODPROMOT, DIA) ON COMMIT PRESERVE ROWS;

CREATE VOLATILE TABLE VT_VENTAS_PP_DEDUP AS (
    SELECT CODDOC, CODPROMOT, DIA
    FROM (
        SELECT CODDOC, CODPROMOT, DIA,
               ROW_NUMBER() OVER (PARTITION BY CODDOC, CODPROMOT, DIA ORDER BY CODDOC) AS rn
        FROM DLAB_GEC.M_EXP_VENTAS_PP
        WHERE TRIM(CAST(MESDESEMBOLSO AS VARCHAR(10))) = '{PERIODO}'
    ) t WHERE rn = 1
) WITH DATA PRIMARY INDEX (CODDOC, CODPROMOT, DIA) ON COMMIT PRESERVE ROWS;

CREATE VOLATILE TABLE VT_VENTAS_EC_DEDUP AS (
    SELECT CODDOC, CODPROMOT, DIA
    FROM (
        SELECT CODDOC, CODPROMOT, DIA,
               ROW_NUMBER() OVER (PARTITION BY CODDOC, CODPROMOT, DIA ORDER BY CODDOC) AS rn
        FROM DLAB_GEC.M_EXP_VENTAS_EC
        WHERE TRIM(CAST(MESDESEMBOLSO AS VARCHAR(10))) = '{PERIODO}'
    ) t WHERE rn = 1
) WITH DATA PRIMARY INDEX (CODDOC, CODPROMOT, DIA) ON COMMIT PRESERVE ROWS;

CREATE VOLATILE TABLE VT_VENTAS_CDEUDA_DEDUP AS (
    SELECT CODDOC, CODPROMOT, DIA
    FROM (
        SELECT CODDOC, CODPROMOT, DIA,
               ROW_NUMBER() OVER (PARTITION BY CODDOC, CODPROMOT, DIA ORDER BY CODDOC) AS rn
        FROM DLAB_GEC.M_EXP_VENTAS_CD
        WHERE TRIM(CAST(MESDESEMBOLSO AS VARCHAR(10))) = '{PERIODO}'
    ) t WHERE rn = 1
) WITH DATA PRIMARY INDEX (CODDOC, CODPROMOT, DIA) ON COMMIT PRESERVE ROWS;

CREATE VOLATILE TABLE VT_VENTAS_SEG_DEDUP AS (
    SELECT CODDOC, CODPROMOT, DIA
    FROM (
        SELECT CODDOC, CODPROMOT, DIA,
               ROW_NUMBER() OVER (PARTITION BY CODDOC, CODPROMOT, DIA ORDER BY CODDOC) AS rn
        FROM DLAB_GEC.M_EXP_VENTAS_SEG
        WHERE TRIM(CAST(MESDESEMBOLSO AS VARCHAR(10))) = '{PERIODO}'
    ) t WHERE rn = 1
) WITH DATA PRIMARY INDEX (CODDOC, CODPROMOT, DIA) ON COMMIT PRESERVE ROWS;

-- 2. Limpieza preventiva del periodo en la tabla histórica final
DELETE FROM DLAB_GEC.M_EXP_PILOTO_NO_VENTA WHERE PERIODO = '{PERIODO}';

-- 3. Inserción Persistente en Tabla Histórica Final
INSERT INTO DLAB_GEC.M_EXP_PILOTO_NO_VENTA (
    PERIODO,
    ID_CONTACTO,
    DNI,
    REG_EV,
    NOM_ASESOR,
    FECHA_LLAMADA,
    COLA,
    TIPIFICACION,
    DURACION,
    T_SILENCIO,
    PCT_SILENCIO,
    FLAG_MANEJA_OBJECION,
    FLAG_OBJ_TASA_ALTA,
    FLAG_OBJ_LO_PENSARA,
    FLAG_OBJ_SIN_INTERES,
    FLAG_OBJ_COMPETENCIA,
    FLAG_OBJ_ENDEUDAMIENTO,
    FLAG_OBJ_OCUPADO,
    FLAG_OBJ_MALA_EXP,
    FLAG_OBJ_MEMBRESIA,
    FLAG_CIERRE_SPEECH,
    FLAG_VENTA_REAL,
    PRODUCTO_VENTA_REAL,
    DIAGNOSTICO_GESTION
)
SELECT 
    '{PERIODO}' AS PERIODO,
    stg.ID_CONTACTO,
    stg.DNI,
    stg.REG_EV,
    stg.NOM_ASESOR,
    CAST(stg.FECHA_LLAMADA AS DATE) AS FECHA_LLAMADA,
    stg.COLA,
    stg.TIPIFICACION,
    stg.DURACION,
    stg.T_SILENCIO,
    stg.PCT_SILENCIO,
    
    -- Manejo de Objeciones (Flag)
    CASE WHEN COALESCE(stg.MDO_GENERAL, stg.MDO_TLV, 0) > 0 THEN 1 ELSE 0 END AS FLAG_MANEJA_OBJECION,
    
    -- Detección de Objeciones Principales (Flags)
    CASE WHEN stg.OBJ_TASA_ALTA > 0 THEN 1 ELSE 0 END AS FLAG_OBJ_TASA_ALTA,
    CASE WHEN stg.OBJ_LO_PENSARA > 0 THEN 1 ELSE 0 END AS FLAG_OBJ_LO_PENSARA,
    CASE WHEN stg.OBJ_SIN_INTERES > 0 THEN 1 ELSE 0 END AS FLAG_OBJ_SIN_INTERES,
    CASE WHEN stg.OBJ_COMPETENCIA > 0 THEN 1 ELSE 0 END AS FLAG_OBJ_COMPETENCIA,
    CASE WHEN stg.OBJ_ENDEUDAMIENTO > 0 THEN 1 ELSE 0 END AS FLAG_OBJ_ENDEUDAMIENTO,
    CASE WHEN stg.OBJ_OCUPADO > 0 THEN 1 ELSE 0 END AS FLAG_OBJ_OCUPADO,
    CASE WHEN stg.OBJ_MALA_EXP > 0 THEN 1 ELSE 0 END AS FLAG_OBJ_MALA_EXP,
    CASE WHEN stg.OBJ_MEMBRESIA > 0 THEN 1 ELSE 0 END AS FLAG_OBJ_MEMBRESIA,
    
    -- Cierre en Audio (Flag)
    CASE WHEN COALESCE(stg.CIERRE_TRANSV, stg.CIERRE_TLV, 0) > 0 THEN 1 ELSE 0 END AS FLAG_CIERRE_SPEECH,
    
    -- Flag Venta Real en Teradata
    CASE 
        WHEN tc.CODDOC IS NOT NULL OR pp.CODDOC IS NOT NULL OR ec.CODDOC IS NOT NULL 
          OR cdeuda.CODDOC IS NOT NULL OR seg.CODDOC IS NOT NULL THEN 1
        ELSE 0
    END AS FLAG_VENTA_REAL,
    
    -- Producto Colocado
    CASE 
        WHEN tc.CODDOC IS NOT NULL THEN 'TARJETA DE CREDITO'
        WHEN pp.CODDOC IS NOT NULL THEN 'PRESTAMO PERSONAL'
        WHEN ec.CODDOC IS NOT NULL THEN 'EXTRACASH'
        WHEN cdeuda.CODDOC IS NOT NULL THEN 'COMPRA DE DEUDA'
        WHEN seg.CODDOC IS NOT NULL THEN 'SEGURO'
        ELSE 'SIN VENTA'
    END AS PRODUCTO_VENTA_REAL,
    
    -- Diagnóstico Automatizado de Calidad e Insights
    CASE 
        WHEN (tc.CODDOC IS NOT NULL OR pp.CODDOC IS NOT NULL OR ec.CODDOC IS NOT NULL OR cdeuda.CODDOC IS NOT NULL)
             AND (COALESCE(stg.MDO_GENERAL, stg.MDO_TLV, 0) > 0)
            THEN 'VENTA RESCATADA (MANEJO DE OBJECION EXITOSO)'
            
        WHEN (tc.CODDOC IS NOT NULL OR pp.CODDOC IS NOT NULL OR ec.CODDOC IS NOT NULL OR cdeuda.CODDOC IS NOT NULL)
            THEN 'VENTA CONFORME'
            
        WHEN (tc.CODDOC IS NULL AND pp.CODDOC IS NULL AND ec.CODDOC IS NULL AND cdeuda.CODDOC IS NULL)
             AND UPPER(stg.TIPIFICACION) LIKE '%NO CALIFICA%' 
             AND stg.OBJ_TASA_ALTA > 0
            THEN 'FUGA / TIPIFICACION ERRONEA (RECHAZO POR TASA)'
            
        WHEN (tc.CODDOC IS NULL AND pp.CODDOC IS NULL AND ec.CODDOC IS NULL AND cdeuda.CODDOC IS NULL)
             AND stg.OBJ_LO_PENSARA > 0
            THEN 'NO VENTA - LEAD EN SEGUIMIENTO (LO PENSARA)'
            
        WHEN (tc.CODDOC IS NULL AND pp.CODDOC IS NULL AND ec.CODDOC IS NULL AND cdeuda.CODDOC IS NULL)
             AND (COALESCE(stg.OBJ_TASA_ALTA, stg.OBJ_SIN_INTERES, stg.OBJ_COMPETENCIA, 0) > 0)
             AND (COALESCE(stg.MDO_GENERAL, stg.MDO_TLV, 0) = 0)
            THEN 'NO VENTA - FALTA DE REBATIMIENTO'
            
        ELSE 'NO VENTA REGULAR'
    END AS DIAGNOSTICO_GESTION

FROM DLAB_GEC.M_EXP_STAGE_NO_VENTA stg
LEFT JOIN VT_VENTAS_TC_DEDUP tc 
    ON stg.DNI = tc.CODDOC AND stg.REG_EV = tc.CODPROMOT AND EXTRACT(DAY FROM stg.FECHA_LLAMADA) = tc.DIA
LEFT JOIN VT_VENTAS_PP_DEDUP pp 
    ON stg.DNI = pp.CODDOC AND stg.REG_EV = pp.CODPROMOT AND EXTRACT(DAY FROM stg.FECHA_LLAMADA) = pp.DIA
LEFT JOIN VT_VENTAS_EC_DEDUP ec 
    ON stg.DNI = ec.CODDOC AND stg.REG_EV = ec.CODPROMOT AND EXTRACT(DAY FROM stg.FECHA_LLAMADA) = ec.DIA
LEFT JOIN VT_VENTAS_CDEUDA_DEDUP cdeuda 
    ON stg.DNI = cdeuda.CODDOC AND stg.REG_EV = cdeuda.CODPROMOT AND EXTRACT(DAY FROM stg.FECHA_LLAMADA) = cdeuda.DIA
LEFT JOIN VT_VENTAS_SEG_DEDUP seg 
    ON stg.DNI = seg.CODDOC AND stg.REG_EV = seg.CODPROMOT AND EXTRACT(DAY FROM stg.FECHA_LLAMADA) = seg.DIA;

-- 4. Liberación de Espacio: Limpieza de tabla stage raw
DELETE FROM DLAB_GEC.M_EXP_STAGE_NO_VENTA ALL;
